In [1]:
import numpy as np
diabetes_train = np.loadtxt("training_diabetes_x_y_train.csv" ,  delimiter=',')
x_train = diabetes_train[: , 1]
y_train = diabetes_train[: , -1]

diabetes_test = np.loadtxt("test_diabetes_x_test.csv" ,  delimiter=',')
x_test = diabetes_test[: , :]



In [2]:
len(diabetes_train)

331

In [3]:
def step_gradient(data , learning_rate , m , c):
    N = len(data)
    m_slope = 0
    c_slope = 0
    for i in range(N):
        x = data[i,0]
        y = data[i,-1]
        m_slope += (-2/N) * (y-m*x-c)*c
        c_slope += (-2/N) * (y-m*x-c)
    new_m = m - learning_rate * m_slope
    new_c = c - learning_rate * c_slope
    return new_m , new_c

In [4]:
def gd(data , learning_rate , num_iteration):
    m = 0
    c = 0
    for i in range(num_iteration):
        m,c = step_gradient(data , learning_rate , m , c)
        print(i , "Cost " , cost(data,m,c))
    return m,c
    

In [5]:
def cost(data , m ,c):
    total_cost = 0
    M = len(data)
    for i in range(M):
        x = data[i,0]
        y = data[i,-1]
        total_cost += (1/M) * ((y-m*x-c)**2)
    return total_cost

In [8]:
def run():
    data = np.loadtxt("training_diabetes_x_y_train.csv" ,  delimiter=',')
    learning_rate = 0.01
    num_iteration = 10
    m,c = gd(data , learning_rate , num_iteration)
    print(m,c)
run()

0 Cost  27408.939418092206
1 Cost  26547.42563294428
2 Cost  25712.177694311635
3 Cost  24904.106021135445
4 Cost  24124.782368688255
5 Cost  23376.291578097665
6 Cost  22661.10318227246
7 Cost  21981.9606959893
8 Cost  21341.786632814375
9 Cost  20743.601486283143
337.52302133534533 27.392158101360362


In [9]:
def step_gradient(data , learning_rate , m , c):
    N = len(data)
    m_slope = 0
    c_slope = 0
    for i in range(N):
        x = data[i,0]
        y = data[i,-1]
        m_slope += (-2/N) * (y-m*x-c)*c
        c_slope += (-2/N) * (y-m*x-c)
   
    new_m = m - learning_rate * m_slope
    new_c = c - learning_rate * c_slope
    return new_m , new_c

In [10]:
def step_gradient_full(data , learning_rate , m ):
    N = len(data)
    m_slope = [0 for i in range(data.shape[1]-1)]
    for i in range(N):
        y = data[i,-1]
        fin_m = 0
        for j in range(data.shape[1]-1):
            x = data[i,j]
            fin_m += m[j] * x
        for j in range(data.shape[1]-1):
            m_slope[j] += (-2/N) * (y-fin_m)*data[i,j]
        
    
    new_m = [0 for i in range(data.shape[1]-1)]

    for i in range(len(m)):
        new_m[i] = m[i] - (learning_rate * m_slope[i])
    
    return new_m 

In [11]:
def gd_full(data , learning_rate , num_iteration):
    m = [0 for i in range(data.shape[1]-1)]
    
    for i in range(num_iteration):
        m = step_gradient_full(data , learning_rate , m )
        print(i , "Cost " , cost_full(data,m))
#         print(m)
    return m
    

In [12]:
def cost_full(data , m):
    total_cost = 0
    M = len(data)
    for i in range(M):
        y = data[i,-1]
        fin_m = 0
        for j in range(data.shape[1]-1):
            x = data[i,j]
            fin_m += m[j] * x
        total_cost += (1/M) * ((y-fin_m)**2)
    return total_cost

In [15]:
def run_full():
    data = np.loadtxt("training_diabetes_x_y_train.csv" ,  delimiter=',')

    learning_rate = 0.0001
    num_iteration = 10
    m = gd_full(data , learning_rate , num_iteration)
    print(m)

In [16]:
run_full()

0 Cost  28296.634423569674
1 Cost  28296.628363773834
2 Cost  28296.622303996122
3 Cost  28296.616244236528
4 Cost  28296.610184495075
5 Cost  28296.60412477175
6 Cost  28296.598065066537
7 Cost  28296.59200537947
8 Cost  28296.58594571054
9 Cost  28296.57988605973
[0.001037272390643856, 0.00015072631620500427, 0.004413797893128777, 0.0025710637951107066, 0.0010351705722485708, 0.0008271633073330733, -0.002461354321444611, 0.002368761598594418, 0.0034664977273606594, 0.002822243010277524]


In [17]:
data = np.loadtxt("training_diabetes_x_y_train.csv" ,  delimiter=',')
data.shape

(331, 11)

In [18]:
m = [2 , 3]
l = 2
m_slope = [5,6]
new_m = [0,0]

for i in range(len(m)):
    new_m[i] = m[i] - (l*m_slope[i])
new_m

[-8, -9]

In [19]:
import numpy as np
from sklearn import preprocessing

In [20]:
x = np.array([[1. , -1 , 2.],
              [2. , 0. , 0.],
              [0. , 1. ,-1.]])

In [21]:
x_scaled = preprocessing.scale(x)

In [22]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [23]:
x_scaled.std(axis = 0)

array([1., 1., 1.])

In [24]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])